//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLexStudio.IntercomServices.Models.Tickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ObjectID { get; set; }
        public string CallerName { get; set; }
        public string Description { get; set; }
        public string BuildingID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string StatusReason { get; set; }
        public TicketStatus Status { get; set; }
        public int Assignee { get; set; }
    }
}
