
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iLexStudio.IntercomServices.Models
{

using System;
    

[Flags]

public enum TicketStatus : int
{

    New = 1,

    Checked = 2,

    Assigned = 4,

    Completed = 8,

    Rejected = 16,

    Closed = 3,

}

}
