
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iLexStudio.IntercomServices.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ticket
{

    public int TicketID { get; set; }

    public string CallerName { get; set; }

    public string Description { get; set; }

    public Nullable<int> AddressID { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string StatusReason { get; set; }

    public Nullable<int> StatusID { get; set; }

    public string Assignee { get; set; }



    public virtual Address Addresses { get; set; }

}

}
